import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  env: {
    NEXT_PUBLIC_STELLAR_RPC_URL: process.env.NEXT_PUBLIC_STELLAR_RPC_URL || "https://soroban-testnet.stellar.org:443",
    NEXT_PUBLIC_USER_MANAGEMENT_CONTRACT: process.env.NEXT_PUBLIC_USER_MANAGEMENT_CONTRACT || "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQAHHXCN3A3M",
    NEXT_PUBLIC_COURSE_REGISTRY_CONTRACT: process.env.NEXT_PUBLIC_COURSE_REGISTRY_CONTRACT || "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQAHHXCN3A3M",
    NEXT_PUBLIC_STELLAR_RPC: process.env.NEXT_PUBLIC_STELLAR_RPC || "https://soroban-testnet.stellar.org:443",
    NEXT_PUBLIC_NETWORK_PASSPHRASE: process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE || "Test SDF Network ; September 2015",
    NEXT_PUBLIC_SOROBAN_RPC_URL: process.env.NEXT_PUBLIC_SOROBAN_RPC_URL || "https://soroban-testnet.stellar.org:443",
    NEXT_PUBLIC_COURSE_ACCESS_CONTRACT_ID: process.env.NEXT_PUBLIC_COURSE_ACCESS_CONTRACT_ID || "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQAHHXCN3A3M",
    NEXT_PUBLIC_COURSE_REGISTRY_CONTRACT_ID: process.env.NEXT_PUBLIC_COURSE_REGISTRY_CONTRACT_ID || "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQAHHXCN3A3M",
    NEXT_PUBLIC_COURSE_REGISTRY_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_COURSE_REGISTRY_CONTRACT_ADDRESS || "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQAHHXCN3A3M",
    NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE: process.env.NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE || "Test SDF Network ; September 2015",
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000/api",
  },
};

export default nextConfig;
